apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: capstoneapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: capstoneapp 
    spec:
      containers:
        - name: capstoneapp 
          image: twongreg.azurecr.io/capstoneapp
          ports:
          - containerPort: 8080