apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: capstone
spec:
  selector:
    matchLabels:
      app: cap-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1      
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cap-app
    spec:
      containers:
      - name: cap-app
        image: k1ck3rtw/udacity-capstone:9
        ports:
        - containerPort: 8080